manifest:
    
  remotes:
    - name: alif
      url-base: https://github.com/alifsemi
    - name: armmbed
      url-base: https://github.com/ARMmbed
    - name: pacotte
      url-base: https://github.com/pa-cotte

  projects:
    - name: zephyr
      remote: alif
      revision: main
      repo-path: zephyr_alif
      import:
        name-allowlist:
          - segger       
          - liblc3
          - mbedtls
          - hal_alif   
          - hal_ethos_u
          - tflite-micro
          - hal_st

    - name: mcuboot_alif
      remote: alif
      repo-path: mcuboot_alif
      path: bootloader/mcuboot
      revision: zas-2.x

    - name: cmsis_alif
      remote: alif
      revision: 85f6b92af0f6ac72594d391f895c45cc30847e41
      path: modules/hal/cmsis
      groups:
         - hal
         
    - name: edge-impulse-sdk-zephyr
      description: Edge Impulse SDK for Zephyr
      path: modules/edge-impulse-sdk-zephyr
      revision: v1.79.0
      url: https://github.com/edgeimpulse/edge-impulse-sdk-zephyr
       
  self:
    path: alif
    west-commands: scripts/west-commands.yml