manifest:

  remotes:
    - name: alif
      url-base: https://github.com/alifsemi
    - name: armmbed
      url-base: https://github.com/ARMmbed
    - name: pacotte
      url-base: https://github.com/pa-cotte

  projects:
    - name: zephyr
      remote: alif
      repo-path: zephyr_alif
      revision: v2.3.0
      import:
        name-allowlist:
          - hal_alif
          - hal_ethos_u
          - hal_infineon
          - segger
          - liblc3
          - mbedtls
          - littlefs
          - fatfs
          - hal_nordic
          - tinycrypt
          - open-amp
          - libmetal

    - name: mcuboot_alif
      remote: alif
      repo-path: mcuboot_alif
      path: bootloader/mcuboot
      revision: zas-2.x

    - name: cmsis_alif
      remote: alif
      revision: 85f6b92af0f6ac72594d391f895c45cc30847e41
      path: modules/hal/cmsis
      groups:
         - hal
       
  self:
    path: alif
    west-commands: scripts/west-commands.yml