# --- SYSTEM ---
CONFIG_CPP=y
CONFIG_STD_CPP17=y
CONFIG_NEWLIB_LIBC=y
# CONFIG_NEWLIB_LIBC_FLOAT_PRINTF=y

# CONFIG_REQUIRES_FULL_LIBC=y
CONFIG_REQUIRES_FULL_LIBCPP=y

# CONFIG_NEWLIB_LIBC_MIN_REQUIRED_HEAP_SIZE=8192

# --- MEMORY ---

CONFIG_MAIN_STACK_SIZE=8192
# CONFIG_ISR_STACK_SIZE=16384
CONFIG_HEAP_MEM_POOL_SIZE=262144
CONFIG_NEWLIB_LIBC_MIN_REQUIRED_HEAP_SIZE=8192
# CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=16384

# CONFIG_CACHE_MANAGEMENT=y
CONFIG_PICOLIBC=y
CONFIG_PICOLIBC_IO_FLOAT=y

# --- LOGGING ---
CONFIG_LOG=y
CONFIG_LOG_MODE_IMMEDIATE=y

# --- UART ---
# CONFIG_SERIAL=y
# CONFIG_UART_CONSOLE=y

# --- SENSORS ---
CONFIG_GPIO=y
CONFIG_I2C=y
CONFIG_SENSOR=y
CONFIG_LIS2DUX12=y

# --- ETHOS-U55  ---
CONFIG_ARM_ETHOS_U=y
CONFIG_ARM_ETHOS_U55_256=y

# CONFIG_LOG_DEFAULT_LEVEL=4

CONFIG_CMSIS_DSP=y
CONFIG_CMSIS_NN=y

# CONFIG_FPU=y
# CONFIG_FPU_SHARING=y


CONFIG_CMSIS_DSP_STATISTICS=y
CONFIG_CMSIS_DSP_TRANSFORM=y


CONFIG_CMSIS_DSP_MATRIX=y

CONFIG_CMSIS_DSP_FASTMATH=y
CONFIG_CMSIS_DSP_COMPLEXMATH=y
CONFIG_CBPRINTF_FP_SUPPORT=y
# CONFIG_CMSIS_DSP_FASTMATH=y
# CONFIG_CMSIS_DSP_COMPLEXMATH=y

# CONFIG_ETHOS_U_NPU_TIMEOUT=60000
# CONFIG_ETHOS_U_NPU_CACHE_SIZE=393216

CONFIG_ARM_MPU=y
CONFIG_MPU_ALLOW_FLASH_WRITE=y
# CONFIG_TENSORFLOW_LITE_MICRO=y



CONFIG_ARM_ETHOS_U_LOG_LEVEL_DBG=y

