CONFIG_LOG_DEFAULT_LEVEL=3
CONFIG_BOOT_SWAP_USING_MOVE=y

# # #### Flash configuration for MRAM, Shell and MCUBoot (from Alif support - ticket ACS-1639) ####
CONFIG_OSPI_FLASH_IS25WX=n
CONFIG_OSPI=n
CONFIG_USE_ALIF_HAL_OSPI=n

# # #### MRAM Flash configuration ####
CONFIG_MRAM_FLASH_ALIF=y